# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30af679fbc5a55ed065d5b0d288ba10454b6c1fec0a187b2679567bafe0db57531a871347e6c7e813518e13d42508b7871ed061b3a2adcb67caf1b29d4a51f99

test:
  secret_key_base: 6f834570a7e5e5232d1caf8c029545ccf1540a53ab698cd7f95d3b345abc0828aa9f0f78b8ee31b09600bc0274b7759b1445c2aaf0846244f8a06199d3bbd942

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
